name: Qodana Scan
on:
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
