name: Qodana Scan
on:
  pull_request:
  push:
    - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
